import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, UnifrakturMaguntia,Libre_Baskerville, Merriweather} from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"; // 
import NavbarFooterWrapper from "@/component/NavbarFooterWrapper";
import AppProviders from "@/store/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400","500","600","700","800","900"], // pick what you need
  variable: "--font-playfair",                   // optional CSS var
});
const blackletter = UnifrakturMaguntia({ 
  variable: "--font-blackletter" ,
  weight: '400', 
  subsets: ['latin'] 
});
export const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"], // Regular + Bold
  style: ["normal", "italic"], // Optional italics
  variable: "--font-libre-baskerville",
});
export const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Light + Regular + Bold
  style: ["normal", "italic"],
  variable: "--font-merriweather",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} ${blackletter.variable} ${libreBaskerville.variable} ${merriweather.variable}`}>
      <body className="flex flex-col min-h-screen antialiased">
        <AppProviders>
        <NavbarFooterWrapper>
        <main className="flex-grow flex flex-col">{children}</main>
       </NavbarFooterWrapper>
       </AppProviders>
       <Toaster position="top-center"/>
      </body>
    </html>
  );
}
